#!/usr/bin/env python3
"""
report.py - render plan.json + results.json into a Markdown report skeleton.

  python3 report.py --plan plan.json --results .readme-intern/run/results.json > .readme-intern/REPORT.md

The skeleton contains <!-- diagnosis:N --> markers where Claude writes the root cause and fix for
each failure. Pure standard library.
"""
import argparse
import json

ICON = {"pass": "✅", "warn": "⚠️", "fail": "❌", "timeout": "⏱️"}
SEV = {"high": "🔴", "medium": "🟠", "low": "⚪"}


def md_cell(s):
    return str(s).replace("|", "\\|").replace("\n", " ⏎ ")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--plan", required=True)
    ap.add_argument("--results", default=None, help="omit for a static-only report")
    args = ap.parse_args()
    plan = json.load(open(args.plan))
    res = json.load(open(args.results)) if args.results else None
    readme = plan.get("readme", "README.md")
    name = plan.get("repo_name", "repo")
    out = []

    if res:
        s = res["summary"]
        planned, ran = s["steps_planned"], s["steps_run"]
        env = res.get("environment", {})
        where = ("fresh `%s` container" % env.get("image")) if env.get("mode") == "docker" else "temp dir with a fresh $HOME (local mode, not fully clean)"
        if s["verdict"] == "pass":
            head = "✅ `%s` works from a clean clone: %d/%d steps passed in %ss" % (readme, ran, planned, res.get("total_seconds", "?"))
        elif s["verdict"] == "setup-error":
            head = "⚠️ Could not start the test environment"
        else:
            ff = s["first_failure"]
            head = "❌ The intern got stuck at step %d of %d (%s line %s)" % (
                [x["id"] for x in res["steps"] if x["id"] != "setup"].index(ff["id"]) + 1, planned, readme, ff["line"])
        out.append("# readme-intern report: %s\n\n**%s**\n" % (name, head))
        out.append("Tested in a %s, following `%s` literally. Only committed files (plus your uncommitted edits) were present: no `.env`, no `node_modules`, no caches.\n" % (where, readme))
        if res.get("setup_error"):
            out.append("> Setup error: `%s`\n" % md_cell(res["setup_error"]))
    else:
        out.append("# readme-intern report: %s (static checks only)\n" % name)

    findings = plan.get("static_findings", [])
    if findings:
        out.append("## Found without running anything\n")
        for f in sorted(findings, key=lambda f: {"high": 0, "medium": 1, "low": 2}[f["severity"]]):
            loc = ("line %s: " % f["line"]) if f.get("line") else ""
            out.append("- %s %s%s" % (SEV[f["severity"]], loc, f["message"]))
        out.append("")

    if res and res["steps"]:
        out.append("## Walkthrough\n")
        out.append("| # | Line | Command | Result | Time |")
        out.append("|---|---|---|---|---|")
        for st in res["steps"]:
            extra = ""
            if st.get("port"):
                extra = " (port %s, HTTP %s)" % (st["port"], st.get("http"))
            elif st.get("reason"):
                extra = " (%s)" % st["reason"]
            out.append("| %s | %s | `%s` | %s%s | %ss |" % (st["id"], st.get("line") or "", md_cell(st["cmd"][:80]),
                                                          ICON.get(st["status"], st["status"]), md_cell(extra), st["duration"]))
        skipped = [x for x in plan["steps"] if not x.get("include", True)]
        if skipped:
            out.append("\n<details><summary>%d README commands not run</summary>\n" % len(skipped))
            for x in skipped:
                out.append("- line %s `%s`: %s" % (x["line"], md_cell(x["cmd"][:80]), x.get("reason", "")))
            out.append("\n</details>")
        out.append("")
        for st in res["steps"]:
            if st["status"] in ("fail", "timeout", "warn"):
                out.append("## %s Step %s: `%s`\n" % (ICON[st["status"]], st["id"], md_cell(st["cmd"][:100])))
                out.append("```text\n%s\n```\n" % "\n".join(st.get("output_tail", "").splitlines()[-25:]))
                out.append("<!-- diagnosis:%s -->\n" % st["id"])

    out.append("## Suggested README changes\n\n<!-- fixes -->\n")
    out.append("---\n_Generated by [readme-intern](https://github.com/IasonTsivos/readme-intern)._")
    print("\n".join(out))


if __name__ == "__main__":
    main()
